#use_frameworks!

target 'MJPlistViewController_Example' do
  pod 'MJPlistViewController', :path => '../'
end

target 'MJPlistViewController_Tests' do
  pod 'MJPlistViewController', :path => '../'

  
end
